dist: trusty
sudo: false
matrix:
  include:
  - os: linux
    language: python
    python: "3.5"
  - os: osx
    env: TRAVIS_PYTHON_VERSION="2.7"

addons:
  apt:
    packages:
    - python3
    - wget
    - libav-tools

before_install:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update; brew install ffmpeg wget; wget https://bootstrap.pypa.io/get-pip.py; python get-pip.py; python -m pip install -U ecell matplotlib jupyter;
  fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    wget https://bootstrap.pypa.io/get-pip.py; python3 get-pip.py; python3 -m pip install -U ecell matplotlib jupyter;
  fi

script:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    jupyter nbconvert --to=html --ExecutePreprocessor.enabled=True --ExecutePreprocessor.timeout=3600 --ExecutePreprocessor.kernel_name='python2' tutorial5.ipynb;
    mkdir surge; mv *.html surge/;
  fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    jupyter nbconvert --to=html --ExecutePreprocessor.enabled=True --ExecutePreprocessor.timeout=3600 --ExecutePreprocessor.kernel_name='python3' tutorial5.ipynb;
    mkdir surge; mv *.html surge/;
  fi
  
deploy:
  provider: surge
  project: ./surge/
  domain: ecell4.surge.sh
  skip_cleanup: true
  
