dist: trusty
sudo: false
matrix:
  include:
  - os: linux
    language: python
    python: "3.5"
#  - os: osx
#     env: TRAVIS_PYTHON_VERSION="2.7"

addons:
  apt:
#    sources:
#    - sourceline: 'ppa:mc3man/trusty-media'
  packages:
  - cmake
  - python3
  - wget
#   - ffmpeg

before_install:
# - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
#     brew update; brew install wget; wget https://bootstrap.pypa.io/get-pip.py; python get-pip.py; python -m pip install -U ecell matplotlib jupyter;
#   fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    wget https://bootstrap.pypa.io/get-pip.py;
    python3 get-pip.py;
    python3 -m pip install -U ecell matplotlib numpy jupyter;
  fi

script:
# - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
#     jupyter nbconvert --to=html --ExecutePreprocessor.enabled=True --ExecutePreprocessor.timeout=3600 --ExecutePreprocessor.kernel_name='python2' *.ipynb;
#     mkdir surge; mv *.html surge/;
#   fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    mkdir build;
    cd build;
    cmake -DCMAKE_INSTALL_PREFIX=./surge ..;
    # jupyter nbconvert --to=html --ExecutePreprocessor.enabled=True --ExecutePreprocessor.timeout=3600 --ExecutePreprocessor.kernel_name='python3' *.ipynb;
    # mkdir surge; mv *.html surge/;
  fi

# deploy:
#   provider: surge
#   project: ./build/surge
#   domain: ecell4.surge.sh
#   skip_cleanup: true
